### ISSUE TITLE
Improve the css of buttons in website and font of text on home page

### ISSUE THREAD

**Issue by PARKHI277** [PARKHI277/My-blogwebsite-using-Nodejs#9]

**Comment by 1Fetcher** [comment]
I would like to work on this, I will fix the design issues, assign this to me and consider it under hacktoberfest.

**Comment by PARKHI277** [comment]
Ohk I am assigning you this issue

**Comment by 1Fetcher** [comment]
> Ohk I am assigning you this issue

Done
